version: '2'
services:
  radius:
    build: .
    domainname: 5eurovpn.com
    ports:
     - "80:80"
     - "443:443"
     - "1812:1812/udp"
    network_mode: "host"
    volumes:
     - ~/mnt-daloradius:/mnt
    env_file: .env

