version: '2'
services:
  radius:
    build: .
    domainname: 5eurovpn.com
    ports:
     - "80:80"
     - "443:443"
     - "1812:1812/udp"
    network_mode: "host"
    volumes:
     - ~/mnt-daloradius:/mnt
     - ~/sslcerts:/etc/apache2/ssl
     - ~/daloradius_api_json:/var/www/html/json_api
     - ~/bin/serf:/usr/local/bin/serf
    env_file: .env

